"""Engineering knowledge rules for IntentForge design review."""

from intentforge.knowledge.compiler import compile_rule, compile_rules
from intentforge.knowledge.capabilities import (
    DEFAULT_CAPABILITY_MANIFEST_RESOURCE,
    CapabilityManifestError,
    load_capabilities,
    load_capability_manifest,
)
from intentforge.knowledge.capability_schema import (
    CapabilityDefinition,
    CapabilityManifest,
    CapabilityMatrix,
    CapabilityMatrixRow,
    CoverageReport,
    EvidenceReference,
)
from intentforge.knowledge.coverage import (
    CapabilityValidationResult,
    build_capability_matrix,
    build_coverage_report,
    validate_capability_manifest,
)
from intentforge.knowledge.evidence_bundles import build_all_evidence_bundles, build_evidence_bundle
from intentforge.knowledge.evidence_registry import (
    DEFAULT_EVIDENCE_MANIFEST_RESOURCE,
    EvidenceManifestError,
    EvidenceRegistry,
    filter_evidence,
    load_evidence_definitions,
    load_evidence_manifest,
    validate_evidence_manifest,
)
from intentforge.knowledge.evidence_resolver import resolve_evidence, verify_evidence
from intentforge.knowledge.evidence_schema import (
    EvidenceBundle,
    EvidenceDefinition,
    EvidenceManifest,
    EvidenceObservation,
    EvidenceResolutionReport,
    EvidenceValidationResult,
    TrustReport,
)
from intentforge.knowledge.evaluator import (
    build_design_metrics,
    evaluate_design,
    evaluate_expression,
    evaluate_parameter_table,
)
from intentforge.knowledge.provenance import RuleProvenance, provenance_from_rule
from intentforge.knowledge.report import KnowledgeReport, make_knowledge_report, write_knowledge_report
from intentforge.knowledge.rationale import generate_design_rationale
from intentforge.knowledge.trust import filter_evidence_bundles, generate_trust_report
from intentforge.knowledge.packs import (
    DEFAULT_BRACKET_PACK_RESOURCES,
    RulePack,
    RulePackRegistry,
    RulePackValidationResult,
    load_default_bracket_rule_packs,
    load_rule_pack,
    load_rule_packs,
    validate_default_rule_packs,
    validate_rule_packs,
)
from intentforge.knowledge.reasoning import (
    ALLOWED_CONFLICT_TYPES,
    ALLOWED_INTERACTION_TYPES,
    ALLOWED_PRIORITIES,
    ALLOWED_STEP_TYPES,
    EngineeringReasoningReport,
    REASONING_ENGINE_VERSION,
    build_engineering_reasoning_report,
    detect_recommendation_contradictions,
    load_golden_cases,
    render_engineering_reasoning_markdown,
    run_golden_case,
    run_reasoning_verification,
    validate_golden_cases,
    validate_recommendation_applicability,
    write_engineering_reasoning_markdown,
    write_engineering_reasoning_report,
)
from intentforge.knowledge.rules import RuleRegistry, load_rules, validate_reasoning_metadata, validate_rule_data
from intentforge.knowledge.schema import CompiledConstraint, DesignKnowledgeRule, KnowledgeFinding

__all__ = [
    "CompiledConstraint",
    "DesignKnowledgeRule",
    "KnowledgeFinding",
    "KnowledgeReport",
    "CapabilityDefinition",
    "CapabilityManifest",
    "CapabilityManifestError",
    "CapabilityMatrix",
    "CapabilityMatrixRow",
    "CapabilityValidationResult",
    "CoverageReport",
    "EvidenceReference",
    "EvidenceDefinition",
    "EvidenceManifest",
    "EvidenceManifestError",
    "EvidenceRegistry",
    "EvidenceObservation",
    "EvidenceBundle",
    "EvidenceResolutionReport",
    "EvidenceValidationResult",
    "TrustReport",
    "EngineeringReasoningReport",
    "RuleProvenance",
    "RulePack",
    "RulePackRegistry",
    "RulePackValidationResult",
    "RuleRegistry",
    "DEFAULT_BRACKET_PACK_RESOURCES",
    "DEFAULT_CAPABILITY_MANIFEST_RESOURCE",
    "DEFAULT_EVIDENCE_MANIFEST_RESOURCE",
    "ALLOWED_CONFLICT_TYPES",
    "ALLOWED_INTERACTION_TYPES",
    "ALLOWED_PRIORITIES",
    "ALLOWED_STEP_TYPES",
    "REASONING_ENGINE_VERSION",
    "build_design_metrics",
    "build_capability_matrix",
    "build_coverage_report",
    "build_evidence_bundle",
    "build_all_evidence_bundles",
    "build_engineering_reasoning_report",
    "compile_rule",
    "compile_rules",
    "detect_recommendation_contradictions",
    "evaluate_design",
    "evaluate_expression",
    "evaluate_parameter_table",
    "filter_evidence",
    "filter_evidence_bundles",
    "generate_trust_report",
    "generate_design_rationale",
    "load_capabilities",
    "load_capability_manifest",
    "load_evidence_definitions",
    "load_evidence_manifest",
    "load_rules",
    "load_default_bracket_rule_packs",
    "load_golden_cases",
    "load_rule_pack",
    "load_rule_packs",
    "make_knowledge_report",
    "provenance_from_rule",
    "render_engineering_reasoning_markdown",
    "run_golden_case",
    "run_reasoning_verification",
    "validate_golden_cases",
    "validate_capability_manifest",
    "validate_evidence_manifest",
    "validate_reasoning_metadata",
    "validate_recommendation_applicability",
    "validate_default_rule_packs",
    "validate_rule_packs",
    "validate_rule_data",
    "resolve_evidence",
    "verify_evidence",
    "write_engineering_reasoning_markdown",
    "write_engineering_reasoning_report",
    "write_knowledge_report",
]
