"""Deterministic assurance claim and argument templates."""

from __future__ import annotations

from typing import Any

from intentforge.assurance.schema import AssuranceArgument, AssuranceClaim, canonical_digest


CLAIM_TEXT = {
    "request_interpreted": ("Request interpreted", "The request was translated into a structured IntentForge design intent."),
    "intent_schema_valid": ("Intent schema valid", "The structured design intent passed the configured IntentForge schema checks."),
    "family_supported": ("CAD family supported", "The selected CAD family is within the declared IntentForge scope."),
    "feature_plan_supported": ("Feature plan recorded", "The feature plan uses the selected supported CAD family and records omitted features."),
    "constraints_compiled": ("Constraints compiled", "The run produced a structured constraint summary from the accepted intent."),
    "engineering_rules_evaluated": ("Engineering rules evaluated", "The current engineering knowledge rules were evaluated for this design."),
    "geometry_generated": ("Geometry generated", "CAD geometry was generated by the deterministic IntentForge generator for this run."),
    "geometry_valid": ("Geometry validation completed", "The generated geometry passed the configured IntentForge geometry validation checks for this run."),
    "topology_inspected": ("Topology inspected", "Topology observations were recorded for this run."),
    "features_recognized": ("Features recognized", "Topology-informed feature recognition produced a result for this run."),
    "engineering_reasoning_completed": ("Engineering reasoning completed", "Deterministic engineering reasoning was produced from evaluated knowledge findings."),
    "requested_edit_preserved_intent": ("Edit intent preserved", "The requested edit was applied while unrelated intent fields were preserved."),
    "unsupported_behavior_rejected": ("Unsupported behavior rejected", "The request was rejected by design before unsupported CAD export."),
    "capability_evidence_available": ("Capability evidence available", "Project-level evidence bundles are available for the exercised declared capabilities."),
    "artifact_integrity_verified": ("Artifact integrity recorded", "Generated artifacts have safe references and verified content hashes."),
    "package_reproducible": ("Logical package identity reproducible", "The audit package logical content identity was reproduced from the same deterministic content."),
    "limitation_disclosed": ("Limitations disclosed", "Known partial support and unsupported boundaries relevant to this run are disclosed."),
}


def make_claim(
    claim_type: str,
    *,
    family: str,
    status: str = "supported",
    stages: list[str] | None = None,
    capability_ids: list[str] | None = None,
    evidence_ids: list[str] | None = None,
    validation_ids: list[str] | None = None,
    artifact_ids: list[str] | None = None,
    rule_ids: list[str] | None = None,
    limitations: list[str] | None = None,
    required_review: bool = False,
    predecessor_hash_pointer: str | None = None,
) -> tuple[AssuranceClaim, AssuranceArgument]:
    title, statement = CLAIM_TEXT[claim_type]
    base = {
        "claim_type": claim_type, "family": family, "status": status,
        "stages": sorted(stages or []), "required_review": required_review,
        "capability_ids": sorted(capability_ids or []), "evidence_ids": sorted(evidence_ids or []),
        "validation_ids": sorted(validation_ids or []), "artifact_ids": sorted(artifact_ids or []),
        "rule_ids": sorted(rule_ids or []), "limitations": sorted(limitations or []),
    }
    if predecessor_hash_pointer is not None:
        base["predecessor_hash_pointer"] = predecessor_hash_pointer
    claim_id = canonical_digest("claim", base)
    argument_payload: dict[str, Any] = {"claim_id": claim_id, "rationale_code": f"{claim_type}_evidence", **base}
    argument_id = canonical_digest("argument", argument_payload)
    argument = AssuranceArgument(
        argument_id=argument_id, claim_id=claim_id, rationale_code=f"{claim_type}_evidence",
        rationale=statement, rule_ids=base["rule_ids"], capability_ids=base["capability_ids"],
        evidence_ids=base["evidence_ids"], validation_ids=base["validation_ids"],
        artifact_ids=base["artifact_ids"], limitation_ids=[], parent_argument_ids=[],
        predecessor_hash_pointer=predecessor_hash_pointer,
        content_id=canonical_digest("argument_content", argument_payload),
    )
    claim_payload = {**base, "claim_id": claim_id, "argument_ids": [argument_id], "statement": statement}
    claim = AssuranceClaim(
        claim_id=claim_id, claim_type=claim_type, title=title, statement=statement, status=status,
        family=family, stages=base["stages"], argument_ids=[argument_id],
        supporting_evidence_ids=base["evidence_ids"], supporting_validation_ids=base["validation_ids"],
        supporting_artifact_ids=base["artifact_ids"], capability_ids=base["capability_ids"],
        rule_ids=base["rule_ids"], limitations=base["limitations"], required_review=required_review,
        predecessor_hash_pointer=predecessor_hash_pointer,
        content_id=canonical_digest("claim_content", claim_payload),
    )
    return claim, argument
