"""Cryptographic Merkle-tree release dossier aggregation for IntentForge."""

from intentforge.dossier.merkle import (
    MERKLE_TREE_VERSION,
    MerkleNode,
    MerkleTree,
    build_merkle_tree,
    merkle_inclusion_proof,
    rebuild_merkle_root,
    verify_merkle_inclusion_proof,
)
from intentforge.dossier.builder import (
    DOSSIER_CHECKSUMS_FILE,
    DOSSIER_ENVELOPE_FILE,
    DOSSIER_LEAF_INDEX_FILE,
    DOSSIER_MANIFEST_FILE,
    DOSSIER_ROLLUP_FILE,
    DOSSIER_SCHEMA_VERSION,
    DossierLeaf,
    DossierRollup,
    ROLLOUP_STATUS_APPROVED,
    ROLLOUP_STATUS_APPROVED_WITH_CONDITIONS,
    ROLLOUP_STATUS_BLOCKED,
    ReleaseDossier,
    ReleaseDossierBuilder,
    build_dossier,
    compute_dossier_rollup,
    write_dossier,
)
from intentforge.dossier.verifier import (
    DOSSIER_VERIFIER_VERSION,
    DossierChildVerification,
    DossierVerificationResult,
    verify_release_dossier,
)

__all__ = [
    "DOSSIER_SCHEMA_VERSION",
    "DOSSIER_CHECKSUMS_FILE",
    "DOSSIER_ENVELOPE_FILE",
    "DOSSIER_LEAF_INDEX_FILE",
    "DOSSIER_MANIFEST_FILE",
    "DOSSIER_ROLLUP_FILE",
    "DOSSIER_VERIFIER_VERSION",
    "MERKLE_TREE_VERSION",
    "DossierChildVerification",
    "DossierLeaf",
    "DossierRollup",
    "DossierVerificationResult",
    "MerkleNode",
    "MerkleTree",
    "ReleaseDossier",
    "ReleaseDossierBuilder",
    "ROLLOUP_STATUS_APPROVED",
    "ROLLOUP_STATUS_APPROVED_WITH_CONDITIONS",
    "ROLLOUP_STATUS_BLOCKED",
    "build_dossier",
    "build_merkle_tree",
    "compute_dossier_rollup",
    "merkle_inclusion_proof",
    "rebuild_merkle_root",
    "verify_merkle_inclusion_proof",
    "verify_release_dossier",
    "write_dossier",
]